name: construction_report_app
description: Construction report application app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - images/first_page.png

  fonts:
    - family: Advent Pro
      fonts:
        - asset: fonts/AdventPro-Regular.ttf

